// Package conf runs one teleconference on top of a MOQ session.
//
// # Naming
//
// Every participant owns a namespace tuple and publishes three tracks
// under it:
//
//	("tlmst", <room>, <participant-id>)
//	    catalog   MSF catalog (§5) — JSON, declares the two media tracks
//	    video     LOC-packaged video frames
//	    audio     LOC-packaged audio frames
//
// Discovery falls out of that layout: a participant announces its own
// namespace with PUBLISH_NAMESPACE and watches the room with
// SUBSCRIBE_NAMESPACE on the prefix ("tlmst", <room>). The relay then
// reports every other participant as a NAMESPACE arrival and their
// departure as NAMESPACE_DONE, so nobody needs a signalling server.
//
// # Stream mapping
//
// Video uses one group per GOP: a keyframe opens a new group, and the
// frames that follow are objects 1..n inside it on a single subgroup
// stream. A relay can therefore drop a whole group under congestion and
// land the subscriber exactly on the next keyframe.
//
// Audio has no keyframes, so it uses a fixed cadence instead — a new
// group every audioGroupObjects frames. Each group's first object carries
// the codec config, which lets a subscriber that joins mid-stream
// configure its decoder from the first object it receives rather than
// waiting for a catalog.
//
// The draft this design borrows its shape from is
// draft-lcurley-moq-hang; it is an idea source, not a spec this
// implements.
package conf

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/floatdrop/moq-go/pkg/moqt/wire"
)

// NamespaceRoot is the first field of every tlmst namespace tuple.
const NamespaceRoot = "tlmst"

// Track names published under a participant's namespace. CatalogTrack
// must be "catalog" — MSF §5 fixes that name.
const (
	VideoTrack = "video"
	AudioTrack = "audio"
)

// audioGroupObjects is how many audio frames share one group. At the
// 20 ms Opus framing WebCodecs produces, 25 objects is a 500 ms group:
// long enough that stream setup is negligible, short enough that losing
// a group costs half a second rather than seconds.
const audioGroupObjects = 25

// timescaleMicros is the LOC Timescale we publish with. WebCodecs
// timestamps are microseconds, so passing them through unscaled keeps the
// encoder's clock intact end to end.
const timescaleMicros = 1_000_000

// Config identifies the local participant and the room it joins.
type Config struct {
	// Relay is the address to dial: "host:port", "moqt://…", or
	// "https://…" for WebTransport.
	Relay string
	Room  string
	// Nickname is the display name shown to other participants. It
	// travels in the catalog, not in the namespace, so it may contain
	// anything and may repeat.
	Nickname string
	// ID is the last field of the local namespace tuple. Generated by
	// NewID when empty.
	ID string
	// Insecure skips TLS certificate verification. Development relays
	// use self-signed certificates, so the app defaults this on.
	Insecure bool
}

// NewID returns a short random participant identifier. It only has to be
// unique within a room, and it becomes a namespace field, so it is hex.
func NewID() (string, error) {
	var raw [5]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("conf: generate participant id: %w", err)
	}
	return hex.EncodeToString(raw[:]), nil
}

// namespaceFor returns the namespace tuple for one participant in a room.
func namespaceFor(room, id string) wire.TrackNamespace {
	return wire.Namespace(NamespaceRoot, room, id)
}

// nsString renders a namespace tuple for logs and map keys.
func nsString(ns wire.TrackNamespace) string {
	parts := make([]string, len(ns))
	for i, f := range ns {
		parts[i] = string(f)
	}
	return strings.Join(parts, "/")
}

// roomPrefix returns the SUBSCRIBE_NAMESPACE prefix that matches every
// participant in a room.
func roomPrefix(room string) wire.TrackNamespace {
	return wire.Namespace(NamespaceRoot, room)
}
