// Package conf runs one teleconference on top of a MOQ session.
//
// # Naming
//
// Every participant owns a namespace tuple and publishes three tracks
// under it:
//
//	("tlmst", <room>, <participant-id>)
//	    catalog   MSF catalog (§5) — JSON, declares the two media tracks
//	    video     LOC-packaged video frames
//	    audio     LOC-packaged audio frames
//
// Discovery falls out of that layout: a participant announces its own
// namespace with PUBLISH_NAMESPACE and watches the room with
// SUBSCRIBE_NAMESPACE on the prefix ("tlmst", <room>). The relay then
// reports every other participant as a NAMESPACE arrival and their
// departure as NAMESPACE_DONE, so nobody needs a signalling server.
//
// # Stream mapping
//
// Video uses one group per GOP: a keyframe opens a new group, and the
// frames that follow are objects 1..n inside it on a single subgroup
// stream. A relay can therefore drop a whole group under congestion and
// land the subscriber exactly on the next keyframe.
//
// Audio has no keyframes, so it uses a fixed cadence instead — a new
// group every audioGroupObjects frames. Each group's first object carries
// the codec config, which lets a subscriber that joins mid-stream
// configure its decoder from the first object it receives rather than
// waiting for a catalog.
//
// The draft this design borrows its shape from is
// draft-lcurley-moq-hang; it is an idea source, not a spec this
// implements.
package conf

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
	"time"

	"github.com/floatdrop/moq-go/pkg/moqt/wire"
)

// NamespaceRoot is the first field of every tlmst namespace tuple.
const NamespaceRoot = "tlmst"

// Track names published under a participant's namespace. CatalogTrack
// must be "catalog" — MSF §5 fixes that name.
const (
	VideoTrack = "video"
	AudioTrack = "audio"
	// VideoLowTrack is a second, smaller encoding of the same camera. Both
	// carry MSF's video role; the name is what tells them apart, and a
	// subscriber takes exactly one of the two.
	VideoLowTrack = "video-low"
)

// KindVideoLow is the track kind the frontend declares the small encoding
// under. Its media frames are ordinary video — only the declaration and the
// handle distinguish the layer.
const KindVideoLow = "videoLow"

// How long to wait before rebuilding a room watch that ended, the ceiling on
// that wait, and how many attempts before the session is declared lost instead.
// Five attempts over roughly fifteen seconds: long enough to ride out a relay
// that is briefly unhappy, short enough that a call which can no longer
// discover anyone does not stay that way.
const (
	watchRetryDelay = 500 * time.Millisecond
	watchRetryMax   = 5 * time.Second
	watchRetryLimit = 5
)

// How long to wait before retrying a track subscription that failed, the
// ceiling on that wait, and how many attempts before giving up and saying so.
const (
	trackRetryDelay = 500 * time.Millisecond
	trackRetryMax   = 5 * time.Second
	trackRetryLimit = 5
)

// joinTimeout bounds the handshake between a dialled session and a built room
// — PUBLISH for three tracks, the first catalog, PUBLISH_NAMESPACE and
// SUBSCRIBE_NAMESPACE. Generous against a slow relay on a slow link, since
// failing a join that would have worked costs a full redial; short enough that
// a relay which answers nothing is abandoned for the next attempt rather than
// held onto for the rest of the call.
const joinTimeout = 15 * time.Second

// How long to wait before retrying a catalog publish, and how many times. The
// delay lengthens with each attempt. Short and few: the catalog is what makes
// this participant decodable, so it is worth pushing at, and a session that
// cannot carry one small object is not going to be fixed by patience.
const (
	catalogRetryDelay = 300 * time.Millisecond
	catalogRetryLimit = 4
)

// audioGroupObjects is how many audio frames share one group. At the
// 20 ms Opus framing WebCodecs produces, 25 objects is a 500 ms group:
// long enough that stream setup is negligible, short enough that losing
// a group costs half a second rather than seconds.
const audioGroupObjects = 25

// timescaleMicros is the LOC Timescale we publish with. WebCodecs
// timestamps are microseconds, so passing them through unscaled keeps the
// encoder's clock intact end to end.
const timescaleMicros = 1_000_000

// Config identifies the local participant and the room it joins.
type Config struct {
	// Relay is the address to dial: "host:port", "moqt://…", or
	// "https://…" for WebTransport.
	Relay string
	Room  string
	// Nickname is the display name shown to other participants. It
	// travels in the catalog, not in the namespace, so it may contain
	// anything and may repeat.
	Nickname string
	// ID is the last field of the local namespace tuple. Generated by
	// NewID when empty.
	ID string
	// Version is the build this participant is running. It travels in the
	// catalog beside the nickname, so a room can be asked what everyone is
	// on — which is the first question when one person's call misbehaves and
	// nobody else's does. Empty leaves the field out of the catalog.
	Version string
	// Insecure skips TLS certificate verification. Development relays
	// use self-signed certificates, so the app defaults this on.
	Insecure bool
}

// NewID returns a short random participant identifier. It only has to be
// unique within a room, and it becomes a namespace field, so it is hex.
func NewID() (string, error) {
	var raw [5]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("conf: generate participant id: %w", err)
	}
	return hex.EncodeToString(raw[:]), nil
}

// namespaceFor returns the namespace tuple for one participant in a room.
func namespaceFor(room, id string) wire.TrackNamespace {
	return wire.Namespace(NamespaceRoot, room, id)
}

// nsString renders a namespace tuple for logs and map keys.
func nsString(ns wire.TrackNamespace) string {
	parts := make([]string, len(ns))
	for i, f := range ns {
		parts[i] = string(f)
	}
	return strings.Join(parts, "/")
}

// roomPrefix returns the SUBSCRIBE_NAMESPACE prefix that matches every
// participant in a room.
func roomPrefix(room string) wire.TrackNamespace {
	return wire.Namespace(NamespaceRoot, room)
}
